
#comments

# application.properties (.dot or tab-based) OR application.yml (tab-based only) are needed.
# only one of both necessary.
# application.properties wins if there are 2 files.
spring:
  banner:
    location: classpath:banner.txt
    charset: UTF-8
jpa:
  show-sql: true

custom:
  prop:hello